In [1]:
import pandas as pd
import numpy as np

In [3]:
# Read Data
train = pd.read_csv("train_values.csv")
print("Length of train", len(train))
train[:5]

Length of train 260601

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,802906,6,487,12198,2,30,6,5,t,r,...,0,0,0,0,0,0,0,0,0,0
1,28830,8,900,2812,2,10,8,7,o,r,...,0,0,0,0,0,0,0,0,0,0
2,94947,21,363,8973,2,10,5,5,t,r,...,0,0,0,0,0,0,0,0,0,0
3,590882,22,418,10694,2,10,6,5,t,r,...,0,0,0,0,0,0,0,0,0,0
4,201944,11,131,1488,3,30,8,9,t,r,...,0,0,0,0,0,0,0,0,0,0

In [8]:
train_labels = pd.read_csv("train_labels.csv")
len(train_labels)
train_labels[:5]
train_Y = train_labels["damage_grade"]

In [7]:
test_values = pd.read_csv("test_values.csv")
test_values[:5]

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,300051,17,596,11307,3,20,7,6,t,r,...,0,0,0,0,0,0,0,0,0,0
1,99355,6,141,11987,2,25,13,5,t,r,...,1,0,0,0,0,0,0,0,0,0
2,890251,22,19,10044,2,5,4,5,t,r,...,0,0,0,0,0,0,0,0,0,0
3,745817,26,39,633,1,0,19,3,t,r,...,0,0,1,0,0,0,0,0,0,0
4,421793,17,289,7970,3,15,8,7,t,r,...,0,0,0,0,0,0,0,0,0,0

In [11]:
for x in train.columns:
    print(x)

building_id
geo_level_1_id
geo_level_2_id
geo_level_3_id
count_floors_pre_eq
age
area_percentage
height_percentage
land_surface_condition
foundation_type
roof_type
ground_floor_type
other_floor_type
position
plan_configuration
has_superstructure_adobe_mud
has_superstructure_mud_mortar_stone
has_superstructure_stone_flag
has_superstructure_cement_mortar_stone
has_superstructure_mud_mortar_brick
has_superstructure_cement_mortar_brick
has_superstructure_timber
has_superstructure_bamboo
has_superstructure_rc_non_engineered
has_superstructure_rc_engineered
has_superstructure_other
legal_ownership_status
count_families
has_secondary_use
has_secondary_use_agriculture
has_secondary_use_hotel
has_secondary_use_rental
has_secondary_use_institution
has_secondary_use_school
has_secondary_use_industry
has_secondary_use_health_post
has_secondary_use_gov_office
has_secondary_use_use_police
has_secondary_use_other

In [37]:
train.dtypes

building_id                                int64
geo_level_1_id                             int64
geo_level_2_id                             int64
geo_level_3_id                             int64
count_floors_pre_eq                        int64
age                                        int64
area_percentage                            int64
height_percentage                          int64
land_surface_condition                    object
foundation_type                           object
roof_type                                 object
ground_floor_type                         object
other_floor_type                          object
position                                  object
plan_configuration                        object
has_superstructure_adobe_mud               int64
has_superstructure_mud_mortar_stone        int64
has_superstructure_stone_flag              int64
has_superstructure_cement_mortar_stone     int64
has_superstructure_mud_mortar_brick        int64
has_superstructure_cement_mortar_brick     int64
has_superstructure_timber                  int64
has_superstructure_bamboo                  int64
has_superstructure_rc_non_engineered       int64
has_superstructure_rc_engineered           int64
has_superstructure_other                   int64
legal_ownership_status                    object
count_families                             int64
has_secondary_use                          int64
has_secondary_use_agriculture              int64
has_secondary_use_hotel                    int64
has_secondary_use_rental                   int64
has_secondary_use_institution              int64
has_secondary_use_school                   int64
has_secondary_use_industry                 int64
has_secondary_use_health_post              int64
has_secondary_use_gov_office               int64
has_secondary_use_use_police               int64
has_secondary_use_other                    int64
dtype: object

In [97]:
from sklearn.preprocessing import OneHotEncoder
cols = ["legal_ownership_status", "plan_configuration", 
       "position", "roof_type", "other_floor_type", 
       "foundation_type", "land_surface_condition",
       "geo_level_id_1"]

# drop building_id 

object_cols = ["land_surface_condition", 
       "foundation_type",
       "ground_floor_type",
       "other_floor_type",
       "position", 
        "legal_ownership_status",
        "roof_type", "plan_configuration"]

int64_cols = [col for col in train.columns if col not in object_cols]

In [98]:
one = OneHotEncoder().fit(train[object_cols])
one_values = one.transform(train[object_cols]).toarray()

In [99]:
object_values = pd.DataFrame( one_values, columns=one.get_feature_names() )
object_values["building_id"] = train["building_id"]

In [106]:
train_clean = object_values.join(train[int64_cols], how="left", on="building_id",
                  lsuffix="objective")

In [107]:
for x in train_clean.columns:
    print(x)

x0_n
x0_o
x0_t
x1_h
x1_i
x1_r
x1_u
x1_w
x2_f
x2_m
x2_v
x2_x
x2_z
x3_j
x3_q
x3_s
x3_x
x4_j
x4_o
x4_s
x4_t
x5_a
x5_r
x5_v
x5_w
x6_n
x6_q
x6_x
x7_a
x7_c
x7_d
x7_f
x7_m
x7_n
x7_o
x7_q
x7_s
x7_u
building_idobjective
building_id
geo_level_1_id
geo_level_2_id
geo_level_3_id
count_floors_pre_eq
age
area_percentage
height_percentage
has_superstructure_adobe_mud
has_superstructure_mud_mortar_stone
has_superstructure_stone_flag
has_superstructure_cement_mortar_stone
has_superstructure_mud_mortar_brick
has_superstructure_cement_mortar_brick
has_superstructure_timber
has_superstructure_bamboo
has_superstructure_rc_non_engineered
has_superstructure_rc_engineered
has_superstructure_other
count_families
has_secondary_use
has_secondary_use_agriculture
has_secondary_use_hotel
has_secondary_use_rental
has_secondary_use_institution
has_secondary_use_school
has_secondary_use_industry
has_secondary_use_health_post
has_secondary_use_gov_office
has_secondary_use_use_police
has_secondary_use_other

In [108]:
train_clean = train_clean.drop(["building_idobjective", "building_id"], axis=1)

## Naive Bayes

In [110]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score

train_X = train_clean

clf = GaussianNB()
clf.fit(X=train_X, y=train_Y)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [104]:
train_Y.values

array([3, 2, 3, ..., 3, 2, 3])

In [105]:
train_X.dtypes

x0_n                             float64
x0_o                             float64
x0_t                             float64
x1_h                             float64
x1_i                             float64
                                  ...
has_secondary_use_industry         int64
has_secondary_use_health_post      int64
has_secondary_use_gov_office       int64
has_secondary_use_use_police       int64
has_secondary_use_other            int64
Length: 68, dtype: object

In [115]:
for x in train_X.columns:
    print(train_X[x].dtype)

float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64

In [120]:
df = train_X.copy()
df["Y"] = train_Y.values

In [121]:
df.to_csv("training_clean.csv")

In [119]:
train_Y.values

array([3, 2, 3, ..., 3, 2, 3])

In [122]:
df2 = df.dropna()

In [125]:
data_X = df2.drop("Y", axis=1)
data_Y = df2["Y"]

clf = GaussianNB()
clf.fit(X=data_X, y=data_Y)

from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, data_X, data_Y, cv=10)
print('Scores:', scores)
print('Accuracy:', scores.mean()*100)

Scores: [0.41808952 0.40747577 0.41470543 0.40978311 0.40870635 0.41578219
 0.40830769 0.41415385 0.41446154 0.40953846]
Accuracy: 41.21003916557216

In [127]:
from sklearn.naive_bayes import MultinomialNB

data_X = df2.drop("Y", axis=1)
data_Y = df2["Y"]

clf = MultinomialNB()
clf.fit(X=data_X, y=data_Y)

from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, data_X, data_Y, cv=10)
print('Scores:', scores)
print('Accuracy:', scores.mean()*100)

Scores: [0.49361637 0.47915705 0.4780803  0.46762037 0.49976927 0.45439163
 0.474      0.48261538 0.47830769 0.48215385]
Accuracy: 47.89711902310887

In [133]:
data_Y.value_counts()

2    37010
3    21770
1     6226
Name: Y, dtype: int64

In [135]:
tmp = pd.read_csv("train_labels.csv")

In [138]:
tmp["damage_grade"].value_counts()

2    148259
3     87218
1     25124
Name: damage_grade, dtype: int64

In [139]:
148259 / len(tmp)

0.5689118614280068